<?php

    include("Class/View/Form/ClassForm.php");
	include("Cabecalho/Cabecalho.php");

    /*  1. PEGAR TODAS AS MESAS RESERVADAS NO BANCO DE DADOS NAQUELE DIA E PREENCHE-LOS EM RADIOS,
    CASO SEJA RECONHECIDO UM GET, ELE MOSTRARA APENAS A MESA PASSADA PELO GET (POIS SIGNIFICA QUE
    HOUVE REDIRECIONAMENTO DA TELA FORM_INICIAR_MESA.PHP).

    2. LISTAR TODOS OS PRATOS, DRINKS E BEBIDAS EM RADIOS.

    3. PREENCHER SELECT COM OS ATENDENTES CADASTRADOS

    DEVERA REDIRECIONAR PARA CADASTRO_PEDIDO.PHP
    */
?>